name: EntityPlugin
version: '${project.version}'
main: me.shadow_warrior_.entityplugin.EntityPlugin
api-version: 1.19
authors: [ shadow_warrior_ ]
description: Entites
commands:
  entity:
    usage: <command>
